apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: fabliciosoares/mynginx:latest  # Use seu usuário do Docker Hub
        imagePullPolicy: Always               # Garante que ele baixe a versão nova
        ports:
        - containerPort: 80
