name: MyApp

on:
  push:
    branches:
      - develop

jobs:
  CallReusablePipeline:
    uses: fablicio/pipeline-templates/.github/workflows/reusable-pipeline.yml@main
    with:
      image_name: "fabliciosoares/myapp"
    secrets: inherit
    env:
      DOCKER_USERNAME: \${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: \${{ secrets.DOCKER_PASSWORD }}
