name: MyApp

on:
  push:
    branches:
      - develop

jobs:
  CallReusablePipeline:
    uses: fablicio/pipeline-templates/.github/workflows/reusable-pipeline.yml@main
    secrets: inherit
    with:
      image_name: "fabliciosoares/myapp"
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
