name: MyApp

on:
  push:
    branches:
      - develop

jobs:
  CallReusablePipeline:
    # Ajuste o caminho abaixo se necessário
    uses: fablicio/pipeline-templates/.github/workflows/reusable-pipeline.yml@main
    with:
      docker_username: "fabliciosoares"
      image_name: "fabliciosoares/web-app"
    secrets: # Passagem obrigatória de segredos para workflows reutilizáveis
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
